const passport = require("passport");
const GoogleStrategy = require("passport-google-oauth20").Strategy;
const mongoose = require("mongoose");
const keys = require("../config/keys");

const User = mongoose.model("users"); // Access Mongoose's User model class

passport.serializeUser((user, done) => {
  done(null, user.id); // No error, send user ID generated by MongoDB. This info will uniquely identify user in follow-up requests.
});

// Authenticate users with Google Strategy. Function in second argument is where app can get user details, create new record in database, etc.
passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: "/auth/google/callback",
    },
    (accessToken, refreshToken, profile, done) => {
      // (Async query) Attempt to find one user where googleId is equal to profile.id. Returns a Promise.
      User.findOne({ googleId: profile.id }).then((existingUser) => {
        if (existingUser) {
          // We already have a record with given profile's ID, skip user creation
          done(null, existingUser); // First argument: no error; second argument: send along existingUser
        } else {
          // Create new Model Instance of a User (one discrete record) and save it (otherwise it won't persist in the database), then take new user successfully saved in db and call done function.
          new User({ googleId: profile.id })
            .save()
            .then((user) => done(null, user));
        }
      });
    }
  )
);
